###
POST http://localhost:8081/emc/patients/add
Content-Type: application/json

{"firstName": "Added By", "lastName": "HTTP POST", "sex": "f", "address": "www.google.com", "phoneNumber": "02-03-04"}

###
POST http://localhost:8081/emc/patients/add/all
Content-Type: application/json

[
  {"firstName": "Nikita", "lastName": "Smitt", "sex": "m", "address": "Zmerenka", "phoneNumber": "321-456"},
  {"firstName": "Yura", "lastName": "Gorban", "sex": "m", "address": "Lutizhz", "phoneNumber": "045-321"},
  {"firstName": "John", "lastName": "Vakula", "sex": "m", "address": "Irpen", "phoneNumber": "085-222"},
  {"firstName": "Serena", "lastName": "Leonidova", "sex": "f", "address": "Irpen", "phoneNumber": "085-333"}
]

###
GET http://localhost:8081/emc/patients/show/all

<> 2021-11-04T233125.200.json
<> 2021-11-04T233103.200.json
<> 2021-11-04T233044.200.json
<> 2021-11-04T233011.200.json

###
GET http://localhost:8081/emc/patients/show/4


###
PUT http://localhost:8081/emc/patients/update
Content-Type: application/json

{
  "id": 4,
  "firstName": "New first",
  "lastName": "New last",
  "sex": "New sex",
  "address": "New addr.",
  "phoneNumber": "New 02-03-04"
}

###
DELETE http://localhost:8081/emc/patients/delete/11

###
DELETE http://localhost:8081/emc/patients/delete
Content-Type: application/json

{
  "id": 8

}


###
POST http://localhost:8081/emc/doctors/add
Content-Type: application/json

{
  "firstName": "Added",
  "lastName": "ByRest",
  "sex": "f",
  "address": "www.google.com",
  "phoneNumber": "02-03-04",
  "speciality": "hacker"
}


###
GET http://localhost:8081/emc/doctors/show/all

<> 2021-11-04T233003.200.json

###
GET http://localhost:8081/emc/doctors/show/3

<> 2021-11-04T232946.200.json
<> 2021-11-04T232625.200.json

###
GET http://localhost:8081/emc/doctors/show/ByFullName
Content-Type: application/json

{
  "firstName": "Artem",
  "lastName": "Poroh"
}


###
PUT http://localhost:8081/emc/doctors/update
Content-Type: application/json

{
  "id": 3,
  "firstName": "Artem",
  "lastName": "Poroh",
  "sex": "m",
  "address": "Lviv",
  "phoneNumber": "046-321",
  "speciality": "optometrist"
}

<> 2021-11-04T232938.200.json


###
DELETE http://localhost:8081/emc/doctors/delete/7

###
DELETE http://localhost:8081/emc/doctors/delete
Content-Type: application/json

{
  "id": 3
}


